-- Game state assets
Assets = 
{
	[0] = 
	{type = "texture", id = "triforce", 				file = "./Assets/ItemSprites/triforcePieces.png"}, 
	{type = "texture", id = "map", 						file = "./Assets/Backgrounds/entire_worldmap_single_image.png"}, 
	{type = "texture", id = "level_1", 					file = "./Assets/Backgrounds/Level1.png"}, 
	{type = "texture", id = "items", 					file = "./Assets/ItemSprites/Items.png"}, 
	{type = "texture", id = "hud_holder", 				file =  "./Assets/HUDSprites/hudHolder.png"}, 
	{type = "texture", id = "hud_hearts", 				file =  "./Assets/Backgrounds/hearts.png"}, 
	{type = "texture", id = "hud_words", 				file =  "./Assets/HUDSprites/HUD_words.png"}, 
	{type = "texture", id = "world_location", 			file =  "./Assets/HUDSprites/world_location.png"}, 
	{type = "texture", id = "locator", 					file =  "./Assets/HUDSprites/location.png"}, 
	{type = "texture", id = "npcs", 					file =  "./Assets/NPCSprites/npcs.png"}, 
	{type = "texture", id = "enemies", 					file =  "./Assets/EnemySprites/sprites_enemies.png"}, 
	{type = "texture", id = "octorok", 					file =  "./Assets/EnemySprites/octorok.png"}, 
	{type = "texture", id = "moblin", 					file =  "./Assets/EnemySprites/moblin.png"}, 
	{type = "texture", id = "darknut", 					file =  "./Assets/EnemySprites/darknut.png"}, 
	{type = "texture", id = "leever", 					file =  "./Assets/EnemySprites/leever.png"}, 
	{type = "texture", id = "enemy_death", 				file =  "./Assets/EnemySprites/EnemyDeath.png"}, 
	{type = "texture", id = "player_death", 			file =  "./Assets/PlayerSprites/player_death.png"}, 
	{type = "texture", id = "numbers", 					file =  "./Assets/Fonts/numbers.png"}, 
	{type = "texture", id = "full_heart", 				file =  "./Assets/ItemSprites/full_heart.png"}, 
	{type = "texture", id = "Dungeon_Tiles", 			file =  "./Assets/Tilemaps/Tiles/Dungeon_Tiles.png"}, 
	{type = "soundFX", id = "magic_rod", 				file =  "./Assets/sounds/MagicalRod.wav"}, 
	{type = "soundFX", id = "boomerang_arrow", 			file = "./Assets/sounds/Arrow_Boomerang.wav"}, 
	{type = "soundFX", id = "candle", 					file =  "./Assets/sounds/Candle.wav"}, 
	{type = "soundFX", id = "bomb_drop", 				file =  "./Assets/sounds/Bomb_Drop.wav"}, 
	{type = "soundFX", id = "bomb_blow", 				file =   "./Assets/sounds/Bomb_Blow.wav"}, 
	{type = "soundFX", id = "sword_slash", 				file =   "./Assets/sounds/Sword_Slash.wav"}, 
	{type = "soundFX", id = "sword_shoot", 				file =   "./Assets/sounds/Sword_Shoot.wav"}, 
	{type = "soundFX", id = "link_hurt", 				file =  "./Assets/sounds/Link_Hurt.wav"}, 
	{type = "soundFX", id = "link_die", 				file =  "./Assets/sounds/Link_Die.wav"}, 
	{type = "soundFX", id = "low_health", 				file =  "./Assets/sounds/LowHealth.wav"}, 
	{type = "soundFX", id = "get_rupee", 				file =  "./Assets/sounds/Get_Rupee.wav"}, 
	{type = "soundFX", id = "get_item", 				file =  "./Assets/sounds/Get_Item.wav"}, 
	{type = "soundFX", id = "stairs", 					file =  "./Assets/sounds/Stairs.wav"}, 
	{type = "soundFX", id = "enemy_hit", 				file =   "./Assets/sounds/Enemy_Hit.wav"}, 
	{type = "soundFX", id = "enemy_die", 				file =   "./Assets/sounds/Enemy_Die.wav"}, 
	{type = "soundFX", id = "fanfare", 					file =   "./Assets/sounds/Fanfare.wav"}, 
	{type = "soundFX", id = "text_fast", 				file =   "./Assets/sounds/text.wav"}, 
	{type = "soundFX", id = "shield", 					file =   "./Assets/sounds/Shield.wav"}, 
	{type = "soundFX", id = "secret", 					file =   "./Assets/sounds/Secret.wav"}, 
	{type = "music",   id = "dungeon", 					file = "./Assets/Music/Dungeon_Theme.mp3"},
	{type = "music",   id = "Overworld", 				file = "./Assets/Music/Overworld_Theme.mp3"},
	
}
