-- Game state assets
Assets = 
{
	[0] = 
	{type = "texture", id = "triforce", 				file = "./assets/ItemSprites/triforcePieces.png"}, 
	{type = "texture", id = "map", 						file = "./assets/Backgrounds/entire_worldmap_single_image.png"}, 
	{type = "texture", id = "level_1", 					file = "./assets/Backgrounds/Level1.png"}, 
	{type = "texture", id = "items", 					file = "./assets/ItemSprites/Items.png"}, 
	{type = "texture", id = "hud_holder", 				file =  "./assets/HUDSprites/hudHolder.png"}, 
	{type = "texture", id = "hud_hearts", 				file =  "./assets/Backgrounds/hearts.png"}, 
	{type = "texture", id = "hud_words", 				file =  "./assets/HUDSprites/HUD_words.png"}, 
	{type = "texture", id = "world_location", 			file =  "./assets/HUDSprites/world_location.png"}, 
	{type = "texture", id = "locator", 					file =  "./assets/HUDSprites/location.png"}, 
	{type = "texture", id = "npcs", 					file =  "./assets/NPCSprites/npcs.png"}, 
	{type = "texture", id = "enemies", 					file =  "./assets/EnemySprites/sprites_enemies.png"}, 
	{type = "texture", id = "octorok", 					file =  "./assets/EnemySprites/octorok.png"}, 
	{type = "texture", id = "moblin", 					file =  "./assets/EnemySprites/moblin.png"}, 
	{type = "texture", id = "darknut", 					file =  "./assets/EnemySprites/darknut.png"}, 
	{type = "texture", id = "leever", 					file =  "./assets/EnemySprites/leever.png"}, 
	{type = "texture", id = "aquamentus", 				file =  "./assets/EnemySprites/aquamentus.png"}, 
	{type = "texture", id = "enemy_death", 				file =  "./assets/EnemySprites/enemyDeath.png"}, 
	{type = "texture", id = "fire_ball", 				file =  "./assets/EnemySprites/enemy_fire_ball.png"}, 
	{type = "texture", id = "player_death", 			file =  "./assets/PlayerSprites/player_death.png"}, 
	{type = "texture", id = "numbers", 					file =  "./assets/Fonts/numbers.png"}, 
	{type = "texture", id = "full_heart", 				file =  "./assets/ItemSprites/full_heart.png"}, 
	{type = "texture", id = "Dungeon_Tiles", 			file =  "./assets/Tilemaps/Tiles/Dungeon_Tiles.png"}, 
	{type = "texture", id = "Overworld_Tiles", 			file =  "./assets/Tilemaps/Tiles/Zelda_overworld.png"}, 
	{type = "soundFX", id = "magic_rod", 				file =  "./assets/sounds/MagicalRod.wav"}, 
	{type = "soundFX", id = "boomerang_arrow", 			file = "./assets/sounds/Arrow_Boomerang.wav"}, 
	{type = "soundFX", id = "candle", 					file =  "./assets/sounds/Candle.wav"}, 
	{type = "soundFX", id = "bomb_drop", 				file =  "./assets/sounds/Bomb_Drop.wav"}, 
	{type = "soundFX", id = "bomb_blow", 				file =   "./assets/sounds/Bomb_Blow.wav"}, 
	{type = "soundFX", id = "sword_slash", 				file =   "./assets/sounds/Sword_Slash.wav"}, 
	{type = "soundFX", id = "sword_shoot", 				file =   "./assets/sounds/Sword_Shoot.wav"}, 
	{type = "soundFX", id = "link_hurt", 				file =  "./assets/sounds/Link_Hurt.wav"}, 
	{type = "soundFX", id = "link_die", 				file =  "./assets/sounds/Link_Die.wav"}, 
	{type = "soundFX", id = "low_health", 				file =  "./assets/sounds/LowHealth.wav"}, 
	{type = "soundFX", id = "get_rupee", 				file =  "./assets/sounds/Get_Rupee.wav"}, 
	{type = "soundFX", id = "get_item", 				file =  "./assets/sounds/Get_Item.wav"}, 
	{type = "soundFX", id = "stairs", 					file =  "./assets/sounds/Stairs.wav"}, 
	{type = "soundFX", id = "enemy_hit", 				file =   "./assets/sounds/Enemy_Hit.wav"}, 
	{type = "soundFX", id = "enemy_die", 				file =   "./assets/sounds/Enemy_Die.wav"}, 
	{type = "soundFX", id = "fanfare", 					file =   "./assets/sounds/Fanfare.wav"}, 
	{type = "soundFX", id = "text_fast", 				file =   "./assets/sounds/text.wav"}, 
	{type = "soundFX", id = "shield", 					file =   "./assets/sounds/Shield.wav"}, 
	{type = "soundFX", id = "secret", 					file =   "./assets/sounds/Secret.wav"}, 
	{type = "soundFX", id = "boss_scream_1", 			file =   "./assets/sounds/Boss_Scream1.wav"}, 
	{type = "soundFX", id = "boss_hit", 				file =   "./assets/sounds/Boss_Hit.wav"}, 
	{type = "soundFX", id = "special_item", 			file =   "./assets/sounds/Special_Item.wav"}, 
	{type = "soundFX", id = "door_unlock", 				file =   "./assets/sounds/Door_Unlock.wav"}, 
	{type = "soundFX", id = "refill_hearts", 			file =   "./assets/sounds/Refill_Loop.wav"}, 
	{type = "music",   id = "triforce_fanfare", 		file =   "./assets/sounds/triforce_fanfare.mp3"}, 
	{type = "music",   id = "dungeon", 					file = "./assets/Music/Dungeon_Theme.mp3"},
	{type = "music",   id = "Overworld", 				file = "./assets/Music/Overworld_Theme.mp3"},
	
}
